using GymSystem.BLL.Interfaces.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GymSystem.BLL.Services.Business
{
    public class PlanValidator
    {
        public void ValidatePlan(AIGeneratedPlan plan)
        {
            // التحقق من التمارين
            if (plan.Exercises == null || !plan.Exercises.Any())
            {
                throw new Exception("No exercises generated by the AI.");
            }

            foreach (var exercise in plan.Exercises)
            {
                if (string.IsNullOrEmpty(exercise.Name) || exercise.Sets <= 0 || exercise.Reps <= 0)
                {
                    throw new Exception($"Invalid exercise data: {exercise.Name}, Sets: {exercise.Sets}, Reps: {exercise.Reps}");
                }
            }

            // التحقق من خطة التغذية
            if (plan.NutritionPlan == null || plan.NutritionPlan.Meals == null || !plan.NutritionPlan.Meals.Any())
            {
                throw new Exception("No nutrition plan generated by the AI.");
            }

            if (plan.NutritionPlan.Calories <= 0)
            {
                throw new Exception("Invalid total calories in nutrition plan.");
            }

            // بنتاكد إن مجموع السعرات الحرارية للوجبات يساوي أو قريب من الإجمالي
            var totalMealCalories = plan.NutritionPlan.Meals.Sum(m => m.Calories);
            if (Math.Abs(totalMealCalories - plan.NutritionPlan.Calories) > 50) 
            {
                throw new Exception($"Mismatch in nutrition plan calories. Expected: {plan.NutritionPlan.Calories}, Actual: {totalMealCalories}");
            }

            foreach (var meal in plan.NutritionPlan.Meals)
            {
                if (string.IsNullOrEmpty(meal.Name) || meal.Calories <= 0 || meal.Items == null || !meal.Items.Any())
                {
                    throw new Exception($"Invalid meal data: {meal.Name}, Calories: {meal.Calories}");
                }
            }
        }
    }
}
