using GymSystem.BLL.Interfaces.Business;

namespace GymSystem.BLL.Services.Business
{
    public class PlanValidator
    {
        public void ValidatePlan(AIGeneratedPlan plan)
        {
            if (plan == null)
            {
                throw new ArgumentNullException(nameof(plan), "Generated plan cannot be null.");
            }

            if (plan.Exercises == null || !plan.Exercises.Any())
            {
                Console.WriteLine("Warning: No exercises generated by the AI.");
            }

            if (plan.NutritionPlan == null || plan.NutritionPlan.Meals == null || !plan.NutritionPlan.Meals.Any())
            {
                Console.WriteLine("Warning: No nutrition plan generated by the AI.");
            }

            if (plan.NutritionPlan != null && plan.NutritionPlan.Calories < 0)
            {
                throw new ArgumentException("Nutrition plan calories cannot be negative.");
            }
        }
    }
}